stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: "alpine:latest"

# Тестовая работа с shell-командами
test_runner:
  stage: test
  script:
    - echo "Runner работает! Текущая дата:"
    - uname -a

# Проверка работы Docker (если используется Docker executor)
test_docker:
  stage: test
  script:
    - echo "Проверка Docker внутри Runner:"

# Имитация сборки (артефакт)
build_example:
  stage: build
  script:
    - echo "Создаем тестовый артефакт..."
    - mkdir -p output
    - echo "Это тестовый артефакт" > output/test.txt
  artifacts:
    paths:
      - output/

# Фейковый деплой (для проверки стадий)
deploy_example:
  stage: deploy
  script:
    - echo "Деплой на тестовую среду..."
    - cat output/test.txt
    - echo "Успех! Runner полностью работоспособен."
  only:
    - main  # Запускать только для ветки main
