stages:
  - lint
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

before_script:
  - python --version
  - pip install --upgrade pip

# 🔍 Линтер (pylint)
lint:
  stage: lint
  script:
    - pip install pylint
    - pylint app.py
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# 🧪 Тесты (если добавишь их в папку tests/)
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest || echo "нет тестов"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# 🐳 Docker build и push
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

# 🚀 Деплой (если нужно — через Ansible или SSH)
# здесь пока placeholder
deploy:
  stage: deploy
  script:
    - echo "Здесь будет деплой. Например, ansible-playbook или ssh-сценарий."
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

