stages:
  - build
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/<твой_путь_проекта>/flask-auction

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
  only:
    - main  # или master, в зависимости от ветки

deploy:
  stage: deploy
  image: alpine/ansible:latest
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H your.server.ip >> ~/.ssh/known_hosts
    - ansible-playbook -i inventory.ini deploy.yml --extra-vars "image_tag=$CI_COMMIT_SHORT_SHA"
  only:
    - main
