stages:
  - check
  - test

# 1. Проверка синтаксиса (lint)
lint:
  stage: check
  script:
    - echo "🔍 Запуск линтера..."
    - if [ -f "package.json" ]; then npm install && npm run lint; fi       # JavaScript (ESLint)
    - if [ -f "requirements.txt" ]; then pip install pylint && pylint .; fi # Python (Pylint)
    - if [ -f "Gemfile" ]; then bundle install && rubocop; fi              # Ruby (RuboCop)
    - if [ -f "*.sh" ]; then shellcheck *.sh; fi                           # Bash (ShellCheck)
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  # только для main-ветки

# 2. Запуск тестов (простая команда)
test:
  stage: test
  script:
    - echo "🧪 Запуск тестов..."
    - if [ -f "package.json" ]; then npm test; fi         # JavaScript
    - if [ -f "pytest.ini" ]; then pytest; fi             # Python
    - if [ -f "Rakefile" ]; then bundle exec rspec; fi    # Ruby
    - if [ -f "go.mod" ]; then go test ./...; fi          # Go
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"  # для всех пушах
