stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  script:
    - pip install pylint
    - pylint app.py

test:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install pytest
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t flask-site:latest .

deploy:
  stage: deploy
  script:
    - echo "Здесь будет деплой"

